name: test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: ['14', '16']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Update node-gyp for Node.js 14 on Windows
        if: matrix.os == 'windows-latest' && matrix.node == '14'
        run: |
          $node_path = Get-Command node | Select-Object -ExpandProperty Source | Split-Path
          cd "$node_path\node_modules\npm\node_modules\npm-lifecycle"
          npm install node-gyp@latest

      - name: Build
        run: npm install && npm run build

      - name: Test
        run: npm test
